language: node_js
node_js:
  - '8'
  - '6'
  - '4'
matrix:
  include:
    - node_js: 8
      env: INTEGRATION=true
  allow_failures:
    - node_js: 8
      env: INTEGRATION=true
before_install:
  - npm i -g npm
script:
  - if [ "$INTEGRATION" = true ]; then npm run integration else npm test; fi
after_success: npm run coveralls
